Repository gutierreztineo/RebroteSolution, pull requests merged in 2020-07, with the labels that each got.

#7 agregar historia de usuario 6,8,14
  Desarrollo/SMZR/Análisis/SMZR_HU_14.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_6.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_8.docx
Labels: documentation

#8 Adición del documento de negocio
  Desarrollo/SMZR/Negocio/SMZR_DN.docx
Labels: documentation

#9 Historia 1
  Desarrollo/SMZR/Análisis/SMZR_HU_1.docx
Labels: documentation

#10 cambio nomenclatura
  Desarrollo/SMZR/Análisis/SMZR_HU_06.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_08.docx
Labels: good first issue

#11 Renombrar Archivo
  Desarrollo/SMZR/Análisis/SMZR_HU_01.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_02.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_03.docx
Labels: documentation, good first issue

#13 Agregar cronograma
  Desarrollo/SMZR/Gestión/SMZR_CA.xlsx
Labels: documentation

#14 Historias Usuario 07, 10 y 15
  Desarrollo/SMZR/Análisis/SMZR_HU_07.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_10.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_15.docx
Labels: documentation

#16 historia de usuario 19
  Desarrollo/SMZR/Análisis/SMZR_HU_19.doc
Labels: documentation

#15 Ajuste de HU
  Desarrollo/SMZR/Análisis/SMZR_HU_03.docx
Labels: documentation

#17 borrar historia 19, crear 17
  Desarrollo/SMZR/Análisis/SMZR_HU_17.doc
Labels: documentation

#18 Agregar HU 16
  Desarrollo/SMZR/Análisis/SMZR_HU_16.docx
Labels: documentation

#21 Actualizacion de Cronograma SMZR_CA.xlsx
  Desarrollo/SMZR/Gestión/SMZR_CA.xlsx
Labels: documentation

#23 Edicion HU 9,12 y 17
  Desarrollo/SMZR/Análisis/SMZR_HU_09.doc
  Desarrollo/SMZR/Análisis/SMZR_HU_12.doc
  Desarrollo/SMZR/Análisis/SMZR_HU_17.doc
Labels: bug

#28 Actualizacion de HU 7 10 15
  Desarrollo/SMZR/Análisis/SMZR_HU_07.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_10.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_15.docx
Labels: documentation

#31 Editar HU 9 12 17
  Desarrollo/SMZR/Análisis/SMZR_HU_09.doc
  Desarrollo/SMZR/Análisis/SMZR_HU_12.doc
  Desarrollo/SMZR/Análisis/SMZR_HU_17.doc
Labels: bug

#34 Agregar historia de usuario 18, actualización de historia de usuario 08
  Desarrollo/SMZR/Análisis/SMZR_HU_08.docx
  Desarrollo/SMZR/Análisis/SMZR_HU_18.docx
Labels: documentation

#39 Adición de documento de arquitectura
  Desarrollo/SMZR/Análisis/SMZR_DAS.docx
Labels: documentation

#40 Modificación de la vista despliegue
  Desarrollo/SMZR/Análisis/SMZR_DAS.docx
Labels: documentation

#51 Agregar historias de usuario 05, 11, 16, y 18
  LíneaBase/SMZR/Linea Base 01/SMZR_HU_05.docx
  LíneaBase/SMZR/Linea Base 01/SMZR_HU_11.docx
  LíneaBase/SMZR/Linea Base 01/SMZR_HU_16.docx
  LíneaBase/SMZR/Linea Base 01/SMZR_HU_18.docx
Labels: documentation

#60 Agregar Cronograma de Actividades a Linea Base 1
  LíneaBase/SMZR/Linea Base 01/SMZR_CA.xlsx
Labels: documentation

#71 actualizacion de cronograma de actividades, documento de requisitos en linea base
  Desarrollo/SMZR/Gestión/SMZR_CA.xlsx
  LíneaBase/SMZR/Linea Base 01/SMZR_CA.xlsx
  LíneaBase/SMZR/Linea Base 01/SMZR_DR.docx
Labels: documentation

#72 actualización de cronograma de actividades
  Desarrollo/SMZR/Gestión/SMZR_CA.xlsx
  LíneaBase/SMZR/Linea Base 01/SMZR_CA.xlsx
Labels: documentation
